### ISSUE TITLE
pencv was not initialized correctly the will will close

### ISSUE THREAD

**Issue by sarmadm** [ajdroid/facetrackerapp#2]
Hi
I have tried facetracker app on galaxy s6 and huwawei . when the app run asks ofr opencv . after installing opencv the app crashes ( opencv was not initialized correctly the will will close ) . do you have any idea about the solution ?

**Comment by ajdroid** [comment]
Hi, 
The issue is probably with the OS on both phones. This app was linked to OpenCV libraries compatible with Android < 5.0.0 since when I wrote this app, OpenCV did not have support for camera access from the C++ side for newer versions of Android.

**Comment by sarmadm** [comment]
is there are any solution for this issue ?

**Comment by ajdroid** [comment]
You need to find and link an appropriate version of `libnative_camera` for your OS. So for 5.0.0 it would be called something like `libnative_camera_r5.0.0.so`. You can see if the new versions of OpenCV4Android have it. That would be the easiest solution

**Comment by sarmadm** [comment]
what  if my mobile is running android 6.0.1 ?

**Comment by ajdroid** [comment]
See if there is `libnative_camera_r6.0.1.so`
